import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const money = (n) =>
  `Rs. ${Number(n || 0).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

export function exportProfitReportPdf({
  report,
  filters,
  products = [],
}) {
  if (!report) return;

  const doc = new jsPDF("p", "mm", "a4");

  const summary = report.summary || {};
  const rows = report.products || [];

  const selectedProduct = products.find(
    (product) => product._id === filters.productId,
  );

  // ----------------------------------------
  // Header
  // ----------------------------------------

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("PROFIT REPORT", 14, 18);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  doc.text(
    `Generated: ${new Date().toLocaleString("en-IN")}`,
    14,
    25,
  );

  // ----------------------------------------
  // Filter information
  // ----------------------------------------

  let filterText = `Period: ${formatPeriod(filters)}`;

  if (filters.brand) {
    filterText += ` | Brand: ${filters.brand}`;
  } else {
    filterText += " | Brand: All";
  }

  if (selectedProduct) {
    filterText += ` | Product: ${selectedProduct.name}`;
  } else {
    filterText += " | Product: All";
  }

  doc.setFontSize(9);
  doc.text(filterText, 14, 32);

  // ----------------------------------------
  // Summary boxes
  // ----------------------------------------

  const boxY = 40;

  drawSummaryBox(
    doc,
    14,
    boxY,
    43,
    "Quantity",
    Number(summary.totalQuantity || 0).toLocaleString(
      "en-IN",
    ),
  );

  drawSummaryBox(
    doc,
    61,
    boxY,
    43,
    "Sales",
    money(summary.totalSales),
  );

  drawSummaryBox(
    doc,
    108,
    boxY,
    43,
    "Cost",
    money(summary.totalCost),
  );

  drawSummaryBox(
    doc,
    155,
    boxY,
    43,
    "Profit",
    money(summary.totalProfit),
  );

  // ----------------------------------------
  // Profit percentage
  // ----------------------------------------

  const totalCost = Number(summary.totalCost || 0);
  const totalProfit = Number(summary.totalProfit || 0);

  const profitPercentage =
    totalCost > 0
      ? (totalProfit / totalCost) * 100
      : 0;

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");

  doc.text(
    `Overall Profit: ${profitPercentage.toFixed(2)}%`,
    14,
    66,
  );

  // ----------------------------------------
  // Product table
  // ----------------------------------------

  autoTable(doc, {
    startY: 74,

    head: [
      [
        "Product",
        "Brand",
        "Qty",
        "Sales",
        "Cost",
        "Profit",
        "Margin",
      ],
    ],

    body: rows.map((item) => [
      item.name || "—",
      item.brand || "—",
      Number(item.quantity || 0).toLocaleString(
        "en-IN",
      ),
      money(item.sales),
      money(item.cost),
      money(item.profit),
      `${Number(
        item.profitPercentage || 0,
      ).toFixed(2)}%`,
    ]),

    theme: "grid",

    styles: {
      fontSize: 8,
      cellPadding: 3,
      valign: "middle",
    },

    headStyles: {
      fontStyle: "bold",
    },

    columnStyles: {
      0: { cellWidth: 38 },
      1: { cellWidth: 28 },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right" },
      6: { halign: "right" },
    },
  });

  // ----------------------------------------
  // Footer
  // ----------------------------------------

  const pageCount = doc.internal.getNumberOfPages();

  for (let page = 1; page <= pageCount; page++) {
    doc.setPage(page);

    const pageHeight =
      doc.internal.pageSize.getHeight();

    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");

    doc.text(
      `Page ${page} of ${pageCount}`,
      196,
      pageHeight - 10,
      {
        align: "right",
      },
    );

    doc.text(
      "Generated by Billing Software",
      14,
      pageHeight - 10,
    );
  }

  // ----------------------------------------
  // File name
  // ----------------------------------------

  const fileName = buildFileName(filters);

  doc.save(fileName);
}

function drawSummaryBox(
  doc,
  x,
  y,
  width,
  label,
  value,
) {
  doc.roundedRect(
    x,
    y,
    width,
    19,
    2,
    2,
  );

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text(label, x + 3, y + 6);

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(value, x + 3, y + 13);
}

function formatPeriod(filters) {
  if (filters.period === "daily") {
    return `Daily - ${filters.date}`;
  }

  if (filters.period === "monthly") {
    return `Monthly - ${filters.month}/${filters.year}`;
  }

  if (filters.period === "yearly") {
    return `Yearly - ${filters.year}`;
  }

  return "All Time";
}

function buildFileName(filters) {
  let name = "profit-report";

  if (filters.period === "daily") {
    name += `-${filters.date}`;
  }

  if (filters.period === "monthly") {
    name += `-${filters.year}-${String(
      filters.month,
    ).padStart(2, "0")}`;
  }

  if (filters.period === "yearly") {
    name += `-${filters.year}`;
  }

  if (filters.brand) {
    name += `-${sanitize(filters.brand)}`;
  }

  return `${name}.pdf`;
}

function sanitize(value) {
  return String(value)
    .trim()
    .replace(/[^a-zA-Z0-9-_]+/g, "-")
    .replace(/-+/g, "-");
}